#画像のパラメータ
image:
  size: 224
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  batch_size: 32

#モデルのパラメータ
train:
  num_epochs: 1
  #updateするパラメータ名
  update_param_names:
    - features.19.weight
    - features.19.bias
    - features.21.weight
    - features.21.bias
    - features.24.weight
    - features.24.bias
    - features.26.weight
    - features.26.bias
    - features.28.weight
    - features.28.bias
    - classifier.0.weight
    - classifier.0.bias
    - classifier.3.weight
    - classifier.3.bias
    - classifier.6.weight
    - classifier.6.bias


#最適化手法のパラメータ
optimizer:
  algorithm: momentum_SDG
  lr: 0.0001
  momentum: 0.9

#画像のデータが入っているフォルダ(./data/に置く)
data:
  train_dir: /data/skin_data/train
  val_dir: /data/skin_data/val
  test_dir: /data/skin_data/test

#csvファイル(./data/に置く)
csv:
  id: image_id
  label: skin
  train: ISIC-2017_Training_Part3_GroundTruth (1).csv
  val: ISIC-2017_Validation_Part3_GroundTruth.csv
  test: ISIC-2017_Test_v2_Part3_GroundTruth.csv

thershold: 0.6