#画像のパラメータ
image:
  size: 224
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  batch_size: 32

#モデルのパラメータ
train:
  num_epochs: 20
  update_param_names: [fc.weight", "fc.bias"]

#最適化手法のパラメータ
optimizer:
  algorithm: momentum_SDG
  lr: 0.001
  momentum: 0.9

#画像のデータが入っているフォルダ
data:
  train_dir: ISIC-2017_Training_Data
  val_dir: ISIC-2017_Validation_Data

#csvファイル名
csv:
  train: ISIC-2017_Training_Part3_GroundTruth (1).csv
  val: ISIC-2017_Validation_Part3_GroundTruth.csv
  test: ISIC-2017_Validation_Part3_GroundTruth.csv
